version: "3"

volumes:
  volume-postgres:

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: api8inf349
  cache:
    image: redis:5
    ports:
      - 6379:6379